version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      runas: ubuntu
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: ubuntu
