version: 0.0
os: linux
files:
  - source: /mbackend.tar.gz
    destination: /tmp/mbackend.tar.gz
  - source: /scripts
    destination: /tmp/scripts
hooks:
  AfterInstall:
    - location: /tmp/scrpits/after_install.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: /tmp/scripts/start_server.sh
      runas: ubuntu
  ApplicationStop:
    - location: /tmp/scripts/stop_server.sh
      runas: ubuntu
