version: 0.1

phases:
  build:
    commands:
      - node --version && npm --version
      - npm install
      - tar cfz mbackend.tar.gz *
artifacts:
  files:
    - mbackend.tar.gz
    - scripts/*
    - appspec.yml
