version: 0.1

phases:
  build:
    commands:
      - node --version && npm --version
      - npm install
      - npm test
cache:
  paths:
    - 'node_modules/**/*'
reports:
  unit-tests:
    files:
      - xunit.xml
    file-format: JUNITXML
  coverages:
    files:
      - coverage/cobertura-coverage.xml
    file-format: COBERTURAXML
